# Generated by Django 4.1.7 on 2023-03-24 00:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0003_category_listings_imageurl_listings_isactive_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listings',
            name='price',
            field=models.FloatField(),
        ),
    ]
