# Generated by Django 4.1.7 on 2023-04-02 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0004_alter_listings_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='listings',
            name='watchlist',
            field=models.BooleanField(default=False),
        ),
    ]
