# Generated by Django 4.1.7 on 2023-04-10 01:11

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0005_listings_watchlist'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='listings',
            name='watchlist',
        ),
        migrations.AddField(
            model_name='listings',
            name='watchlist',
            field=models.ManyToManyField(blank=True, null=True, related_name='watchlistListing', to=settings.AUTH_USER_MODEL),
        ),
    ]
